### ISSUE TITLE
HashiCorp Partner Provider Program - Initial Review

### ISSUE THREAD

**Issue by cgriggs01** [baidubce/terraform-provider-baiducloud#1]
I’ve taken a look at the provider here and would like to say great work so far! I was able to run the acceptance tests, and they are all passing with 77% code coverage! 👍  I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. If it works better for you, this changes can be added to a separate branch if any changes conflict with your current build process.  The review was done on the master branch at git commit  [f0169fe](https://github.com/baidubce/terraform-provider-baiducloud/commit/f0169fed78174bda9eae1bbea732274cf4aca67d) 

- [x]  One of our Terraform Ecosystem engineers built a linter to help align coding best practices for providers. You should use it along with your development. https://github.com/bflad/tfproviderlint

- [x] The website documentation looks good, there is just one link that must be fixed. In baiducloud.erb  at line 42. I think the file name `appblb.html` should be `appblbs.html`. 

- [x] Your Makefile should be replaced with the GNUmakefile which is standard across all Terraform providers, feel free to copy the [GitHub provider makefile](https://github.com/terraform-providers/terraform-provider-github/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=baiducloud

- [x] The CHANGELOG formatting will have to be updated to conform to the standard provider format since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the next release should be tagged as “1.0.0 (Unreleased)” and will then be updated with a date by the release-bot. 

- [x] You are already using Go Modules to manage the providers dependancies which is great, but in addition to that, we ask that you checkin all the required dependancies into a `vendor/` directory. This is so that our nightly testing environment does ping GitHub for ever dependancies in all 100+ TF providers.

**Comment by gola** [comment]
All checkpoints of this issue have been resolved.

**Comment by cgriggs01** [comment]
Team, 

I have no further feedback and would like to schedule the migration and release of this provider. This will publish the built binary of the provider to releases.hashicorp.com and publish the website documentation to terraform.io. Do you have an objections to starting the release process?

You'll need provide me with a list of whomever will need "write" access of the new repository where the provider will be built under the [terraform-providers/](https://github.com/terraform-providers/) Github organization where all official terraform provider are developed. These individuals will also get access to a TeamCity environment where the acceptances tests of this provider will be run nightly and a Slack channel where the team will be able to request a release built and a HashiCorp engineer will work with you to trigger the release. Can you provide an email and GitHub username? 

Please let me know if you have any questions.

**Comment by gola** [comment]
Thank you very much. 
I have no objection to starting the release process.
The list of developers is as follows:
| GitHub Username | Email |
| ---- | ---- |
| gola | guowei17@baidu.com |
| hefangshi | hefangshi@baidu.com |
| sunzhaochang | sunzhaochang@baidu.com |
| YINChengfeng | yinchengfeng@baidu.com |
