### ISSUE TITLE
Creating a default access key pair when creating a new IAM user

### ISSUE THREAD

**Issue by zhenrong-wang** [baidubce/terraform-provider-baiducloud#17]
Currently, the bce terraform provider doesn't support creating/deleting/listing access key pair. However, our project requires creating a default access key pair when creating a new IAM user. Therefore, we came up with an idea, which only modifies ONE source code file:

_**resource_baiducloud_iam_user.go**_

Here are our modifications:

I. Adding 2 Optional items ("access_key" & "secret_key") to the schema map:

               Schema: map[string]*schema.Schema{
			"unique_id": {
				...
			},
			"name": {
				...
			},
			"description": {
				...
			},
			"force_destroy": {
				...
			},
			"access_key": {
				Type:        schema.TypeString,
				Description: "Default AK.",
				Optional:    true,
			},
			"secret_key": {
				Type:        schema.TypeString,
				Description: "Default SK.",
				Optional:    true,
			},
		},

II. Modify the function of creating a new user:

```
func resourceBaiduCloudIamUserCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.BaiduClient)
	name := d.Get("name").(string)
	description := d.Get("description").(string)
	action := "Create User " + name

	user, err := client.WithIamClient(func(iamClient *iam.Client) (i interface{}, e error) {
		return iamClient.CreateUser(&api.CreateUserArgs{
			Name:        name,
			Description: description,
		})
	})
	if err != nil {
		return WrapErrorf(err, DefaultErrorMsg, "baiducloud_iam_user", action, BCESDKGoERROR)
	}
	addDebug(action, user)

	raw, err := client.WithIamClient(func(iamClient *iam.Client) (i interface{}, e error) {
		return iamClient.CreateAccessKey(name)
	})
	if err != nil {
		return WrapErrorf(err, DefaultErrorMsg, "baiducloud_iam_user", action, BCESDKGoERROR)
	}

	addDebug(action, raw)
	result := raw.(*api.CreateAccessKeyResult)
	d.Set("access_key", result.Id)
	d.Set("secret_key", result.Secret)

	d.SetId(name)
	return resourceBaiduCloudIamUserRead(d, meta)
}

```

III. Test:

I've updated the _resource_baiducloud_iam_user.go_ file and compiled my own version of terraform-provider-baiducloud. It works quite well. Here is my test tf file:

```
 terraform {
  required_providers {
    baiducloud = {
      source  = "baidubce/baiducloud"
      version = "1.19.9"
    }
  }
}

provider "baiducloud" {
  access_key = "b1ec1f4df8********************"
  secret_key = "21910e70************************"
  region = "bj"
}

#The lifecycle part (ignore_changes = [access_key,secret_key] ) is VERY IMPORTANT!
#Without the lifecycle body, the ak and sk will be erased from the terraform.tfstate file at the next apply
#With the lifecycle part, the ak and sk string will not be erased. However, this is NOT secure, because the ak and sk string may leak
#Therefore, it depends on the purpose of the user.
resource "baiducloud_iam_user" "hpc_user" {
  name = "my_user_name_wzr"
  force_destroy = false
  lifecycle {
    ignore_changes = [access_key,secret_key]
  }
}
```

IV. Summary

The method above works. When creating a new user, a default AccessKey pair will be generated and exported to the terraform.tfstate file.

**Comment by zhenrong-wang** [comment]
Please consider combining the idea into the next version. Thanks!
A better idea is to write the ak/sk strings to a temporary text file (i.e. accesskeys.txt), not to the terraform.tfstate
And then ask the users to save the file if the user wants to use the key pair.

**Comment by BenBeng** [comment]
Thank you for the idea, and we'll look into it later.

**Comment by zhenrong-wang** [comment]
When will the resource Access Key be added to the provider?
Thanks!

**Comment by BenBeng** [comment]
After updating to version [v1.19.13](https://github.com/baidubce/terraform-provider-baiducloud/releases/tag/v1.19.13), IAM access keys can be managed through `resource/baidu aws_iam_access_key`.
