### ISSUE TITLE
NAT网关创建spec不要有default值吧？

### ISSUE THREAD

**Issue by c-zhenyu** [baidubce/terraform-provider-baiducloud#18]
[terraform-provider-baiducloud](https://github.com/baidubce/terraform-provider-baiducloud/tree/master)/[baiducloud](https://github.com/baidubce/terraform-provider-baiducloud/tree/master/baiducloud)
/resource_baiducloud_nat_gateway.go

spec：Default:      "small",
这样在不支持普通NAT网关的地方就无法创建了，因为传入cu_num后，spec还是有的，就会导致创建失败，尽快解决

**Comment by BenBeng** [comment]
已经在[v1.19.15](https://github.com/baidubce/terraform-provider-baiducloud/releases/tag/v1.19.15) 版本中修复。
