### ISSUE TITLE
[BUG Report] IAM user and IAM policy failed when the region is not bj

### ISSUE THREAD

**Issue by zhenrong-wang** [baidubce/terraform-provider-baiducloud#19]
When the region in main.tf is not bj, resources IAM user and IAM policy will fail.

TF file content:

terraform {
  required_providers {
    baiducloud = {
      source  = "baidubce/baiducloud"
      version = "~> 1.19.14"
    }
  }
}

provider "baiducloud" {
  access_key = "xxxxxxxxxxxxxxxxx"
  secret_key = "rrrrrrrrrrrrrrrrrrrr"
  region = "bd" #When region is bj, success. When region is not bj, will fail.
}

resource "baiducloud_iam_user" "hpc_user" {
  name = "riz268bhwa"
  force_destroy = true
}

ERROR INFO (Thown out by Terraform):

│ Error: [ERROR] terraform-provider-baiducloud/baiducloud/resource_baiducloud_iam_user.go:80: Resource baiducloud_iam_user Create User kc920akch8 Failed!!! [SDK bce-sdk-go ERROR]:
│ execute http request failed! Retried 3 times, error: Post "http:///v1/user": http: no Host in request URL

**Comment by BenBeng** [comment]
Fixed in version [v1.19.18](https://github.com/baidubce/terraform-provider-baiducloud/releases/tag/v1.19.18)
