### ISSUE TITLE
Error: Failed to install provider

### ISSUE THREAD

**Issue by sys520084** [baidubce/terraform-provider-baiducloud#6]
HI all,
I try to follow this link ( https://registry.terraform.io/providers/baidubce/baiducloud/latest/docs ) to initializing provider  plugins, but I get bellow error:
*******************************************************************************************************
Initializing the backend...

Initializing provider plugins...
- Finding baidubce/baiducloud versions matching "1.10.0"...
- Installing baidubce/baiducloud v1.10.0...

Error: Failed to install provider

Error while installing baidubce/baiducloud v1.10.0: checksum list has
unexpected SHA-256 hash
47468d260f2269cdb476786f45716278fa5b2e9c0b492e1cb01d490cd712f5b7 (expected
2e33e045a47745773aab906fe0e39f7e470d3515e2c387f2796030671f8fe4b0)
*******************************************************************************************************

my client summary is:
OS: macOS Catalina-10.15.6
version: Terraform v0.13.4

**Comment by sys520084** [comment]
anybody is here?

**Comment by gola** [comment]
> anybody is here?

This problem requires the help of HashiCorp engineers. We are contacting HashiCorp to resolve this issue.

**Comment by gola** [comment]
> HI all,
> I try to follow this link ( https://registry.terraform.io/providers/baidubce/baiducloud/latest/docs ) to initializing provider plugins, but I get bellow error:
> 
> Initializing the backend...
> 
> Initializing provider plugins...
> 
> * Finding baidubce/baiducloud versions matching "1.10.0"...
> * Installing baidubce/baiducloud v1.10.0...
> 
> Error: Failed to install provider
> 
> Error while installing baidubce/baiducloud v1.10.0: checksum list has
> unexpected SHA-256 hash
> 47468d260f2269cdb476786f45716278fa5b2e9c0b492e1cb01d490cd712f5b7 (expected
> 2e33e045a47745773aab906fe0e39f7e470d3515e2c387f2796030671f8fe4b0)
> 
> my client summary is:
> OS: macOS Catalina-10.15.6
> version: Terraform v0.13.4

We fixed it by release v1.10.1
